### ISSUE TITLE
Separate.wav is blank

### ISSUE THREAD

**Issue by ChrisCJou** [Lab-info/MelBank#3]
Good Afternoon! Thank you for your previous responses, they were very helpful and I was able to train a model on my voice.

After I had created a new data set and ran the
`python train.py`

After that, I ran `python separator.py` with a new source.wav.
However, it seems like the separate.wav file is blank. Is there a specific format that source.wav needs to be for to run as intended? 

Otherwise, perhaps this was an issue with how I trained it? If you could give any insight, it would be much appreciated. Thank you!

**Comment by averak** [comment]
Sorry for the late contact.

separate.wav file is there any sound at all?
Isn't even a small sound included?

Thanks for the report!
